# Book settings
title: Urban Grammar AI | WP3 - Signature AI
author: Dani Arribas-Bel, Martin Fleischmann
logo: logo.svg

execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/urbangrammarai/signature_ai
launch_buttons:
  binderhub_url: https://mybinder.org
html:
  use_repository_button: true
